### ISSUE TITLE
clipboard.js inclusion

### ISSUE THREAD

**Issue by mudrd8mz** [vfremaux/moodle-auth_ticket#3]
The way how clipboard.js is loaded is wrong and it does not work if the Moodle is not installed in the root of the domain.

**Comment by mudrd8mz** [comment]
The line 

    <script src="<?php $CFG->wwwroot ?>/auth/ticket/js/clipboard/clipboard.js"></script>

should read

    <script src="<?php echo($CFG->wwwroot); ?>/auth/ticket/js/clipboard/clipboard.js"></script>

You are missing the "echo" there.

**Comment by vfremaux** [comment]
Integrated, thanks tomek.
